### ISSUE TITLE
Bundeswehr Equipment Fix 

### ISSUE THREAD

**Issue by NJP695** [CoalitionArma/Coalition-Reforger-Framework#110]
**Describe the bug**
Squad Leaders have double radios, the modded one that gets slotted into the quick items list, and a default mod that sits in the inventory.

Separately, the Red Teamlead for the Squad does not have a radio entirely.

**What Faction**
BW

**What Loadout/Role**
SL / TL

**Screenshots**
![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/73005931/a5cb13b4-b3d1-4727-9a08-179a77241d7c)

**Additional context**
Discovered during mission 2 of CFC #7. Teamlead radio might be anecdotal/situational, and might not be an issue at all.

**Comment by tanaaKa** [comment]
Fixed in https://github.com/CoalitionArma/Coalition-Reforger-Framework/pull/117

**Comment by NJP695** [comment]
BW SLs still have doubled radios. Third mission in CFC 9 is where the issue came up again
