### ISSUE TITLE
Soviet Equipment Suggestion

### ISSUE THREAD

**Issue by NJP695** [CoalitionArma/Coalition-Reforger-Framework#111]
**Describe the bug**
The Sniper slot for the base game Soviet faction has only an SVD with five magazines in total, and has no secondary. Given these mags lack tracers, therefore a small guaranteed number of those few rounds are needed to range the targets, and that the SVD also serves as the sole weapon of the Sniper slot, it seems as though there are not enough ammunition OR there is no secondary with which to defend oneself when they run out of ammo.

**What Faction**
USSR

**What Loadout/Role**
Sniper

**Screenshots**
![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/73005931/43fca14b-e0df-4170-84ec-984519f7ca49)

**Comment by tanaaKa** [comment]
Fixed in https://github.com/CoalitionArma/Coalition-Reforger-Framework/pull/117
