### ISSUE TITLE
Discussion: Grenadier Replacement

### ISSUE THREAD

**Issue by NJP695** [CoalitionArma/Coalition-Reforger-Framework#122]
**Describe the bug**
Not a single rifleman, Teamlead, or Squadlead on BW has a grenade launcher. There are squadmembers with M4s, but no underbarrel grenade launchers throughout the entire infantry platoon.

**What Faction**
BW

**What Loadout/Role**
SL, TL, Grenadier

**Comment by tanaaKa** [comment]
I really don't want grenadiers to be a normal class. I'm open minded to have something else tho. Standard modern squad:

SL
MED
TL (R)
AR
AAR
TL (G)
RAT
RAT
(CLS Maybe?)

**Comment by tanaaKa** [comment]
Last member in green team will be Rifleman (Demo)
