### ISSUE TITLE
give modern RU forces AR PKM instead of RPK

### ISSUE THREAD

**Issue by Arkangel-Vigilamus** [CoalitionArma/Coalition-Reforger-Framework#124]
Rpk bad, give PKM.

**Comment by tanaaKa** [comment]
https://github.com/CoalitionArma/Coalition-Reforger-Framework/pull/139

**RU MSV**
- AR RPK to PKM
- AAR to PKM mags
- Medic +radio
-  Medic +3smokes
- ALL CLASSES +2smokes
- ALL CLASSES +radio
- Pilot +2 violet smokes

**USSR**
- PL +2smoke
- PL +2 grenade
- AR RPK to PKM
- AR +2 grenade
- MEDIC +medical kit
