### ISSUE TITLE
Give leadership long range radio by default.

### ISSUE THREAD

**Issue by Arkangel-Vigilamus** [CoalitionArma/Coalition-Reforger-Framework#125]
On 6/14 session first mission, blufor leadership had short range radios to communicate with their heli's and other elements spread wide across an AO. Leadership, PLT at the very least, should have the max range radio by default to ensure the LOCs are maintained for each team.

**Comment by tanaaKa** [comment]
https://github.com/CoalitionArma/Coalition-Reforger-Framework/commit/4d616df80d69ea53565ba9ee75d4dcb7f0ca72e8

I've used my massively smooth brain to instead tweak hand held radios to be 5k range.
