### ISSUE TITLE
BW Overhaul

### ISSUE THREAD

**Issue by RandAlThor1** [CoalitionArma/Coalition-Reforger-Framework#130]
Inline with trying to improve consistency between factions and across missions please see below for changes that need to be made to the BW loadout to bring it inline with standard. reference here (https://docs.google.com/spreadsheets/d/1cpFU4wZFa2P8NVyqYhY3q3eDcZ1-ZkE5NpPFkasLsGU/edit?usp=sharing)
Please direct feedback here:  https://discord.com/channels/237991125523103747/1251630650063323248

Too ensure accuracy please verify that the loadouts actually load into missions with the correct gear, to avoid carry weight issues.

**Platoon Leader**
- [ ] Needs to be created inline with standard

**Medical Officer**
- [ ] Needs to be created inline with standard

**RTO**
- [ ] Needs to be created inline with standard

**Squad Leader**
- [ ] Rifle mags reduced to total 10 down from total 15. add 1 green and 1 red smoke
- [ ] Either Equip with a M4 with a UGL and provide 3x UGL HE rounds, or supplement with 3 Additional Frag grenades until we have weapons to meet the standard. my preference is the M4
- [ ] Reduce bandages to 2 from 11
- [ ] Add Shovel

**Medic**
- [ ] Requires 4x Smoke grenades, 2 white, 1 purple, 1 green
- [ ] 1 fewer Bandage, 1 fewer Saline, 3 more Torniquets
- [ ] Add Shovel

**Team Lead**
- [ ] Rifle mags reduced to total 10 down from total 14.
- [ ] Copy decision made with squad leader regarding UGLs.
- [ ] Reduce bandages from 6 to 2, remove morphine
- [ ] Add Binos and Shovel

**Grenadier**
- [ ] Needs to be created inline with standard

**Automatic Rifleman**
- [ ] Replace MG3 with M249 Saw, allows distinction between MG and AR roles. Ensure 6-800 rounds for the M249
- [ ] Provide with 2X M67 Frags
- [ ] Reduce bandages from 7 to 2. remove Morphine.

**Assistant Automatic Rifleman**
- [ ] Replace AAR Spare mags to match M249 change, ensure 4-600 rounds.
- [ ] Reduce smoke to 1x white smoke.
- [ ] Reduce bandages from 7 to 2, remove morphine.
- [ ] Add radio

**Rifleman**
- [ ] Change total primary mags from 9 to 10
- [ ] Add additional m67 from 1 to 2, reduce smoke from 2 to 1
- [ ] Reduce bandages from 7 to 2, remove morphine.
- [ ] Add radio, remove duplicate flashlight

**Rifleman Anti-Tank**
- [ ] Change total primary mags from 9 to 10
- [ ] Reduce smokes from 2 to 1
- [ ] Reduce bandages from 7 to 2, remove morphine
- [ ] Add Radio, remove duplicate flashlight

**Assistant Anti-Tank**
- [ ] Needs to be created inline with standard

**Machine Gunner**
- [ ] Needs to be created inline with standard

**Assistant Machine Gunner**
- [ ] Needs to be created inline with standard

**Medium Anti-Tank**
- [ ] Change total primary mags from 9 to 10
- [ ] Swap 3T Heat with EIT, please verify efficacy of these rounds.
- [ ] Remove 1x Smoke
- [ ] Reduce bandages from 7 to 2
- [ ] Remove duplicate flashlight

**Assistant Medium Anti-Tank**
- [ ] Change total primary mags from 9 to 10
- [ ] Swap 3T Heat with EIT, please verify efficacy of these rounds.
- [ ] Remove 1x Smoke
- [ ] Reduce bandages from 7 to 2
- [ ] Add Binos, remove duplicate flashlight

**Sniper**
- [ ] Change total primary mags from 12 to 6, Change secondary mags from 3 to 4
- [ ] Change totals smokes from 2 to 1
- [ ] Remove Morphine

**Spotter**
- [ ] Change primary mags from 13 to 10
- [ ] Change totals smokes from 2 to 1
- [ ] Remove morphine

**Armor Crew**
- [ ] Change primary mags from 7 to 3. 
- [ ] Remove Frag grenades
- [ ] Remove Morphine
- [ ] Add Binos

**Heli Pilot**
- Already meets standard

**Crew Chief**
- Already meets standard

**Comment by Pi123263** [comment]
Should a sniper really only get 3 primary mags total? seems rather low for an entire life

**Comment by RandAlThor1** [comment]
> Should a sniper really only get 3 primary mags total? seems rather low for an entire life

Reference my request for feedback here: https://discord.com/channels/237991125523103747/1251630650063323248

**Comment by Pi123263** [comment]
Sidenote, we should check for medics if we can change the standard assignment of quick slot items to add saline etc, I feel like I saw a component for that while making the loadouts a while ago

**Comment by RandAlThor1** [comment]
BW has been killed, rip in peace.
