### ISSUE TITLE
CDF under BLUFOR

### ISSUE THREAD

**Issue by Geek-x104** [CoalitionArma/Coalition-Reforger-Framework#131]
The CDF appear under blufor in the resource browser and, in the lobby, they have a blue background for their name (image attached)
![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/93412021/ca0a1724-d5c2-466e-ab68-3cd66da5e190)

With the way Tanaka worded his announcement, it seems like they are meant to be OPFOR (see below)
![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/93412021/d865af91-9d2f-41c5-8847-23cacebf53f6)

if this is false then close, otherwise making issue to resolve during gear & loadout fixes currently ongoing.

**Comment by Pi123263** [comment]
From Arma 3 I'd expect CDF to be blufor, but I could be misremembering too

**Comment by JessevGool** [comment]
CDF is BLUFOR in Arma, wiki: https://armedassault.fandom.com/wiki/Chernarussian_Defence_Forces

**Comment by Geek-x104** [comment]
fair play, my bad
