### ISSUE TITLE
[CRF Feature] Keep description tab closed/hidden on map open during mission time

### ISSUE THREAD

**Issue by GHPCee** [CoalitionArma/Coalition-Reforger-Framework#134]
**Is your feature request related to a problem? Please describe.**
I'm frustrated whenever I open the map in big screen and have to hide the mission description tab on the left side of the screen (hidden with 'D' press)

**Describe the solution you'd like**
Maybe have a boolean variable or such to keep the description revealed or hidden for whenever the map is opened by the player.

**Describe alternatives you've considered**
Just been closing the description manually and whatnot.

**Additional context**
![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/169863781/6b2097c2-581e-4725-8420-37ad281bd8a1)

**Comment by tanaaKa** [comment]
Not up to us. This is from reforger lobby:

https://github.com/JiraF4/PlayableSelector
