### ISSUE TITLE
1980s USSR Overhaul

### ISSUE THREAD

**Issue by RandAlThor1** [CoalitionArma/Coalition-Reforger-Framework#135]
Inline with trying to improve consistency between factions and across missions please see below for changes that need to be made to the 1980s USSR loadout to bring it inline with standard. reference here (https://docs.google.com/spreadsheets/d/1cpFU4wZFa2P8NVyqYhY3q3eDcZ1-ZkE5NpPFkasLsGU/edit?usp=sharing)
Please direct feedback here:  https://discord.com/channels/237991125523103747/1251630650063323248

Too ensure accuracy please verify that the loadouts actually load into missions with the correct gear, to avoid carry weight issues.

**Platoon Leader**
- [x] Change Primary Ammo from 9 to 10 mags, Change Sidearm Ammo from 5 to 7 mags, Change UGL count from 5 to 3
- [x] Add 2x RDG-5 (HE Frag), Add 2X RDG-2 (White smoke) and 1x Green smoke 1x Red Smoke
- [x] Remove Morphine
- [x] Add Shovel

**Medical Officer**
- [ ] Needs to be created inline with standard

**Squad Leader**
- [x] Change Primary Mags from 7 to 10. Change UGL from 11 to 3
- [x] Change Frag count from 1 to 2 Change Smoke count from 2 to 1
- [x] Remove Morphine

**Medic**
- [x] Change Primary Mag count from 5 to 8
- [x] Change Smokes from 1 white, to two 2 white 1 green 1 purple
- [x] Change bandages to 12 from 8, Reduce Torniquets from 8 to 4, Reduce morphine from 8 to 6, Change saline from 4 to 5, add medical kit

**Team Lead**
- [ ] Needs to be created inline with standard

**Automatic Rifleman**
- [x] Change RPK-74 for PKM
- [x] Ensure 600 rounds for Primary
- [x] Reduce Frag count to 2, Reduce Smoke count to 1
- [x] Remove Morphine

**Assistant Automatic Rifleman**
- [ ] Needs to be created inline with standard, lower end of spare ammo to ensure AMG has difference with AAR

**Rifleman**
- [x] Change Primary Mag count from 7 to 8.
- [x] Change Frag count to 2, Change Smoke count to 1
- [x] Remove Morphine

**Rifleman Anti-Tank**
- [x] Change Primary Mag count from 5 to 8. Reduce Secondary count from 3 to 2 HEAT rounds
- [x] Change Frag count to 2, Change Smoke count to 1
- [x] Remove Morphine

**Assistant Anti-Tank**
- [x] Change Primary Mag count from 5 to 8. Change Spare Rocket count from 3 to 2.
- [x] Change Frag count to 2, Change smoke count to 1
- [x] Remove Morphine

**Machine Gunner**
- [x] Change Primary Box count from 2 to 8, Change Sidearm Mag Count from 2 to 7
- [x] Change Frag count to 2
- [x] Remove Morphine

**Assistant Machine Gunner**
- [ ] Change Primary Mag count from 5 to 8. Change spare boxes from 3 to 5
- [ ] Change Frag count to 2, Change smoke count to 1
- [ ] Remove Morphine

**Medium Anti-Tank**
- [ ] Needs to be created inline with standard

**Assistant Medium Anti-Tank**
- [ ] Needs to be created inline with standard

**Sniper**
- [ ] Change Primary Mag count from 5 to 12, Change sidearm mag count from 3 to 7
- [ ] Change Frag count to 2, Change smoke count to 1
- [ ] Remove Morphine

**Spotter**
- [ ] Needs to be created inline with standard

**Armor Crew**
- [ ] Change Sidearm Mag count from 4 to 7
- [ ] Remove morphine
- [ ] Add Binos, Add Shovel

**Heli Pilot**
- [ ] Change Sidearm Mag count from 4 to 7

**Crew Chief**
- [ ] Needs to be created inline with standard

**FO**
- [ ] Needs to be created inline with standard

**JTAC**
- [ ] Needs to be created inline with standard

**Comment by tanaaKa** [comment]
Oh fuck I should've used this

**Comment by RandAlThor1** [comment]
> Oh fuck I should've used this

I'll go through and update this with changes u made today

**Comment by RandAlThor1** [comment]
will likely need to be remade, otherwised finished
