### ISSUE TITLE
Opinion: Remove BW Faction

### ISSUE THREAD

**Issue by tanaaKa** [CoalitionArma/Coalition-Reforger-Framework#140]
The BW faction is extremely barebones, which would be fine if it was standalone. However, it has a **massive** dependency on big mods:
- TF Mattock Weapons (554mb)
- TF Mattock Gear (473mb)
- TF Mattock OPFOR (297mb)
- Greg NVG system (bad code)

In my opinion the limited faction is not worth this massive additional 1.3gb add.

**Comment by RandAlThor1** [comment]
BW has been removed
