### ISSUE TITLE
CDF Overhaul

### ISSUE THREAD

**Issue by RandAlThor1** [CoalitionArma/Coalition-Reforger-Framework#145]
Inline with trying to improve consistency between factions and across missions please see below for changes that need to be made to the CDF loadout to bring it inline with standard. reference here (https://docs.google.com/spreadsheets/d/1cpFU4wZFa2P8NVyqYhY3q3eDcZ1-ZkE5NpPFkasLsGU/edit?usp=sharing)
Please direct feedback here:  https://discord.com/channels/237991125523103747/1251630650063323248

Too ensure accuracy please verify that the loadouts actually load into missions with the correct gear, to avoid carry weight issues.

**Platoon Leader**
- [ ] Change Primary Mags from 9 to 10, Change UGL from 3 to 5
- [ ] Change smoke to 2 white, 1 green, 1 red
- [ ] Add Bino, Add Shovel

**Medical Officer**
- [ ] Change Primary mags from 7 to 8
- [ ] Remove frags, Add 1 purple, 1 green smoke
- [ ] Change Medical 12 Bandages, 4 Torniquets, 6 Morphine, 6 EPI, 5 Saline, Keep medical bag
- [ ] Add shovel 

**Squad Leader**
- [ ] Change Primary mags from 7 to 10, Change UGL from 10 to 5
- [ ] Add 1 green one red smoke
- [ ] Add 2 bandages, 1 tourniquet
- [ ] Add Radio
- [ ] Add Map, Compass, Shovel

**Medic**
- [ ] Change Primary mags from 7 to 8
- [ ] Remove frags, Add 1 purple, 1 green smoke
- [ ] Change Medical 12 Bandages, 4 Torniquets, 6 Morphine, 6 EPI, 5 Saline, Keep medical bag
- [ ] Add shovel 

**Team Lead**
- [ ] Change Primary Mags from 9 to 10, Change UGL from 3 to 5
- [ ] Add 1 white smoke
- [ ] Add Shovel

**Automatic Rifleman**
- [ ] Change primary box count from 4 to 5, Change sidearm mags from 1 to 7
- [ ] Change Frags from 3 to 2
- [ ] Add Shovel

**Assistant Automatic Rifleman**
- [ ] Change primary mags from 9 to 10, Change spare boxes from 3 to 4
- [ ] Change frags from 3 to 2
- [ ] Add Shovel

**Rifleman**
- [ ] Change primary mags from 9 to 10
- [ ] Change frags from 3 to 2
- [ ] Add Shovel

**Rifleman Anti-Tank**
- [ ] Change primary mags from 9 to 10
- [ ] Change frags from 3 to 2
- [ ] Add Shovel

**Assistant Anti-Tank**
- [ ] Change primary mags from 9 to 10, Add 2 Spare HEAT rounds for RPG-7V1
- [ ] Change frags from 3 to 2
- [ ] Add Shovel, Add binos

**Machine Gunner**
- [ ] Needs to be created inline with standard

**Assistant Machine Gunner**
- [ ] Needs to be created inline with standard

**Medium Anti-Tank**
- [ ] Needs to be created inline with standard

**Assistant Medium Anti-Tank**
- [ ] Needs to be created inline with standard

**Sniper**
- [ ] Needs to be created inline with standard

**Spotter**
- [ ] Needs to be created inline with standard

**Armor Crew**
- [ ] Needs to be created inline with standard

**Heli Pilot**
- [ ] Needs to be created inline with standard

**Crew Chief**
- [ ] Needs to be created inline with standard

**FO**
- [ ] Needs to be created inline with standard

**JTAC**
- [ ] Needs to be created inline with standard

**Comment by RandAlThor1** [comment]
CDF is kill, rip CDF

**Comment by tanaaKa** [comment]
It's getting a big update soon. https://discord.com/channels/105462288051380224/1118507714537074758

![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/9407533/216c8b1e-2b78-464c-98d9-218aa3efd100)

**Comment by RandAlThor1** [comment]
we will build it from the ground up once this is released
