### ISSUE TITLE
FIA Overhaul

### ISSUE THREAD

**Issue by RandAlThor1** [CoalitionArma/Coalition-Reforger-Framework#146]
Inline with trying to improve consistency between factions and across missions please see below for changes that need to be made to the FIA loadout to bring it inline with standard. reference here (https://docs.google.com/spreadsheets/d/1cpFU4wZFa2P8NVyqYhY3q3eDcZ1-ZkE5NpPFkasLsGU/edit?usp=sharing)
Please direct feedback here:  https://discord.com/channels/237991125523103747/1251630650063323248

Too ensure accuracy please verify that the loadouts actually load into missions with the correct gear, to avoid carry weight issues.

**Platoon Leader**
- [x] Change primary mags from 11 to 10, Change UGL from 3 to 5
- [x] Change frags from 3 to 2, Change smokes to 2 white, 1 green, 1 red
- [ ] Add 1 bandage
- [ ] Add Shovel

**Medical Officer**
- [ ] Change primary mags from 9 to 8
- [ ] Remove Frags, Change smokes to 2 white, 1 green, 1 purple
- [ ] Change medical to 12 bandages, 4 torniquets, 6 morphine, 6 epi, 5 saline

**Squad Leader**
- [ ] Change primary mags from 11 to 10, Change UGL from 4 to 5
- [ ] Change frags from 3 to 2, Change smokes to 2 white, 1 green, 1 red
- [ ] Add 1 bandage
- [ ] Add Bino

**Medic**
- [ ] Change primary mags from 9 to 8
- [ ] Remove Frags, Change smokes to 2 white, 1 green, 1 purple
- [ ] Change medical to 12 bandages, 4 torniquets, 6 morphine, 6 epi, 5 saline

**Team Lead**
- [ ] Needs to be created inline with standard

**Automatic Rifleman**
- [ ] Change primary mags from 12 to 14, Sidearm mags from 3 to 7
- [ ] Change frags from 3 to 2
- [ ] Add Bandage

**Assistant Automatic Rifleman**
- [ ] Change primary mags from 11 to 10, Change spare mags from 5 to 9
- [ ] Add Bandage
- [ ] Add Shovel

**Rifleman**
- [ ] Change primary mags from 11 to 10
- [ ] Change frags from 3 to 2
- [ ] Add Bandage

**Rifleman Anti-Tank**
- [ ] Change primary mags from 11 to 10
- [ ] Change frags from 3 to 1
- [ ] Add Bandage

**Assistant Anti-Tank**
- [ ] Needs to be created inline with standard

**Machine Gunner** 
- [ ] Change primary boxes from 4 to 10. Change sidearm mags from 3 to 7
- [ ] Change frags from 0 to 2
- [ ] Add bandage

**Assistant Machine Gunner**
 - [ ] Change primary mags from 7 to 10, Change spare boxes from 6 to 8
 - [ ] Add bandage
 - [ ] Add Binos

**Medium Anti-Tank**
- [ ] Needs to be created inline with standard

**Assistant Medium Anti-Tank**
- [ ] Needs to be created inline with standard

**Sniper**
- [ ] Needs to be created inline with standard

**Spotter**
- [ ] Needs to be created inline with standard

**Armor Crew**
- [ ] Needs to be created inline with standard

**Heli Pilot**
- [ ] Needs to be created inline with standard

**Crew Chief**
- [ ] Needs to be created inline with standard

**FO**
- [ ] Needs to be created inline with standard

**JTAC**
- [ ] Needs to be created inline with standard

**Comment by tanaaKa** [comment]
https://github.com/CoalitionArma/Coalition-Reforger-Framework/commit/70245bc032646d0c2f8b38d32cbf139b7298eff3

**Comment by RandAlThor1** [comment]
finished
