### ISSUE TITLE
Content update cleanup

### ISSUE THREAD

**Issue by RandAlThor1** [CoalitionArma/Coalition-Reforger-Framework#147]
Remove mission configs for:

- [x] Seitenbuch
- [x] worthy islands
- [x] Gogland

Replace BW Faction or delete mission:

- [x] PIE_RussianSecrecy @Pi123263 
- [x] Chernarus/Breakthrough @tanaaKa

**Comment by Geek-x104** [comment]
Tanaka made cherno/breakthrough

**Comment by tanaaKa** [comment]
https://github.com/CoalitionArma/Coalition-Reforger-Framework/commit/28ceb5b24e4449c4b252764eb32e10bd0af67284

**Comment by RandAlThor1** [comment]
Configs deleted and missions updated
