### ISSUE TITLE
[CRF Improvement] CDF Group Rework

### ISSUE THREAD

**Issue by Pi123263** [CoalitionArma/Coalition-Reforger-Framework#150]
CDF Currently only has a MAT and Infantry Group, should be reworked to have the same variety of groups as the other factions

**Comment by RandAlThor1** [comment]
This is already slated to be done,
reference: https://github.com/CoalitionArma/Coalition-Reforger-Framework/issues/145
Once roles have been created we will begin changes to create all groups for all factions to improve the mission maker experience.
