### ISSUE TITLE
JIP Delete Issue

### ISSUE THREAD

**Issue by tanaaKa** [CoalitionArma/Coalition-Reforger-Framework#172]
Reason: NULL pointer to instance. Variable 'm_id'

Class:      'CRF_SafestartGameModeComponent'
Function: 'DeleteRedundantUnitsSlowly'
Stack trace:
scripts/Game/Systems/CRF_SafeStart.c:385 Function DeleteRedundantUnitsSlowly
scripts/Game/Systems/CRF_SafeStart.c:385 Function OnUpdate

**Comment by Njpatman** [comment]
This typically only happens when a player takes a slot and then unslots. I will look into it when I get back.
