### ISSUE TITLE
Safestart Issue

### ISSUE THREAD

**Issue by tanaaKa** [CoalitionArma/Coalition-Reforger-Framework#173]
Reason: NULL pointer to instance. Variable 'controlledEntityKey'

Class:      'CRF_SafestartGameModeComponent'
Function: 'DisableSafeStartEHs'
Stack trace:
scripts/Game/Systems/CRF_SafeStart.c:476 Function DisableSafeStartEHs
scripts/Game/game.c:927 Function OnUpdate

**Comment by Njpatman** [comment]
This typically only happens when a player takes a slot and then unslots. I will look into it when I get back.

**Comment by RandAlThor1** [comment]
Safestart fails to stop bullets within close proximity but stops them if you are farther out

**Comment by Njpatman** [comment]
> Safestart fails to stop bullets within close proximity but stops them if you are farther out

This may be impossible to fix as we have the EH checking and deleting every shot fired from an entity; it's just a stupid fast, and easy function that deletes the projectile on the server, nothing more to quicken or speed up.
