### ISSUE TITLE
[Loadout Bug] USMC Loadouts Missing Items.

### ISSUE THREAD

**Issue by Geek-x104** [CoalitionArma/Coalition-Reforger-Framework#175]
**Describe the bug**
RAT has no launcher.
AR has 200rnds.
AAR has no backpack or extra boxes.

**What Faction**
USMC.

**What Loadout/Role**
RAT, AR and AAR.

**Screenshots**
Will provide if I can find any.

**Additional context**
N/A.

**Comment by Geek-x104** [comment]
@RandAlThor1 made [this](https://discord.com/channels/237991125523103747/468879945293234177/1257115326760357948) an issue so we can find it easier.

**Comment by RandAlThor1** [comment]
Adding my extra notes.

AR no medical will check other
UGL on the M27 is too heavy and can't swap rounds.
demo has no demo.
medics have 10 mags instead of 8

**Comment by RandAlThor1** [comment]
- AR Already had backpack w/ boxes, and medical. will test.
- Demo had packback w/ Demo. will test.
- having trouble modifying the m27 UGL

![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/12282858/50cddfc0-142f-4f8d-b188-729226f7d299)
![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/12282858/f92c843d-9279-48fb-be76-d793fbec814d)

**Comment by RandAlThor1** [comment]
PR here: https://github.com/CoalitionArma/Coalition-Reforger-Framework/pull/177

- rifleman demo had demo on the server, I';m being gaslit
- ar had medical, im still being gaslit

![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/12282858/6ca4e841-b4c4-43c7-8580-8bddae6caae8)

![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/12282858/cba4e62d-8dcb-4994-8075-56ed46d5106f)

**Comment by Geek-x104** [comment]
#117 closed, ticket complete.
