### ISSUE TITLE
Modern Russian Gear Script no Flashlight and Radio

### ISSUE THREAD

**Issue by MrPvTDagger** [CoalitionArma/Coalition-Reforger-Framework#19]
There is an issue with Russian modern loadouts, They are not getting the flashlight and radio even though it in their inv component.
![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/16640037/e6036c5c-d46a-42d0-b05a-5573b7d62ebd)
![image](https://github.com/CoalitionArma/Coalition-Reforger-Framework/assets/16640037/78ca48e0-63fd-45e8-846c-45dc96c26f8f)

**Comment by MrPvTDagger** [comment]
Range finder missing too. There space for them so confused why they aren't there

**Comment by tanaaKa** [comment]
For the flashlights, it looks like there's no slot to attach it. Which should be fixed in https://github.com/CoalitionArma/Coalition-Reforger-Framework/commit/b865a9c09502bfab230d63cb7899bd53564540d9

Please verify in your testing
