### ISSUE TITLE
[CRF Feature] Hide all custom CRF UI elements on "i" button keypress.

### ISSUE THREAD

**Issue by GHPCee** [CoalitionArma/Coalition-Reforger-Framework#209]
When pressing "i" to hide UI elements during spectator viewing, bomb timer countdown, red mission end timer countdown, popup notifications on objective completion, and anything else added with CRF, appear on screen when UI is supposed to be hidden.

Suggesting to have said custom UI elements hidden too.

**Comment by Njpatman** [comment]
I will piggyback off of the reforger lobby hide UI system, I don't know what we can do about popup notifications.
