### ISSUE TITLE
[CRF General Bug] UGL Smokes disappear too soon

### ISSUE THREAD

**Issue by RandAlThor1** [CoalitionArma/Coalition-Reforger-Framework#220]
@Salamiboio 

The UGL smokes pop too soon/don't last long enough when being fired at a longer distance they are gone by the time they land.

**Comment by Salamiboio** [comment]
I'll increase the time they ploom but that's weird, didn't encounter that in testing. Must be new update

**Comment by tanaaKa** [comment]
@Salamiboio Reminder

**Comment by Salamiboio** [comment]
Shit forgot about this will be back to my computer tomorrow will check then

**Comment by RandAlThor1** [comment]
@Salamiboio I am once again asking if you will look into this

**Comment by Salamiboio** [comment]
I can't replicate what you're talking about, in my workbench they work just fine, they deploy at a distance and ploom for awhile.

**Comment by RandAlThor1** [comment]
idk man, go fire them in the server and tell me their fine

**Comment by Salamiboio** [comment]
I don't know then, it's just the flare with smoke particles instead of flares. I think it may just be a server replication issue which is why the BI devs haven't done this yet.

**Comment by Salamiboio** [comment]
I'll look into redoing this not using the flare system and instead just using base game smoke grenades
