### ISSUE TITLE
[CRF General Bug] CDF Set to No Faction

### ISSUE THREAD

**Issue by tanaaKa** [CoalitionArma/Coalition-Reforger-Framework#239]
![image](https://github.com/user-attachments/assets/4f2a4d76-f7cd-463e-89e1-8cfa1f8cfcbf)

CDF faction doesnt have a faction affiliation. Needs set to BLUFOR.

**Comment by Geek-x104** [comment]
Gonna look into this now

**Comment by Geek-x104** [comment]
> Gonna look into this now

gonna fix all the issues with my missions first, then gonna come back to this if it hasn't been resolved.

**Comment by RandAlThor1** [comment]
I'm pretty sure CDF notification settings were set to white. I have changed this to match US settings

**Comment by RandAlThor1** [comment]
tested on server, fixed
