### ISSUE TITLE
[Loadout Bug] USSR 80s MAT rockets are too OP

### ISSUE THREAD

**Issue by tanaaKa** [CoalitionArma/Coalition-Reforger-Framework#276]
MAT only really has dual tandems which isn't useful. It should mainly be 7vm's, og, and maybe 1-2 tandems.

**Comment by RandAlThor1** [comment]
MAT teams in the standard config now have a total of 2x PG7VR, 2X OG7V, 3X PG7VL in the MAT/AMAT total
