### ISSUE TITLE
[CRF General Bug] Grey-out Admin Menu if not CRF mission

### ISSUE THREAD

**Issue by tanaaKa** [CoalitionArma/Coalition-Reforger-Framework#308]
The admin menu and its methods do nothing if the mission isn't a CRF mission. On init, perform a check to see if the module exists in the game world and disable the menu visually if one does not.

**Comment by Njpatman** [comment]
Will move to base game mode so all missions will be able to use the admin menu

**Comment by Salamiboio** [comment]
We would have to create a variant of the menu. As things like respawning and refreshing gear need the gear script system to work.
