### ISSUE TITLE
Map Timer: Add check for game start so timer doesnt count down in slotting

### ISSUE THREAD

**Issue by tanaaKa** [CoalitionArma/Coalition-Reforger-Framework#62]

**Comment by Njpatman** [comment]
There's already checks in place that should make this scenario impossible. Is this just an issue to make sure those checks are working or has someone posted about having that bug?

**Comment by tanaaKa** [comment]
Bro you're the one who brought it up that the map timer warnings were happening during slotting.

**Comment by Njpatman** [comment]
> Bro you're the one who brought it up that the map timer warnings were happening during slotting.

I said in safestart, not slotting. Already pushed a fix for that last Sunday as well.

So, this is a non-issue.
