### ISSUE TITLE
MAT team needs fixes

### ISSUE THREAD

**Issue by Njpatman** [CoalitionArma/Coalition-Reforger-Framework#66]
Radios are by default on local PLT Net.

There are no binos for MAT Asst.

There are no Rockets in MAT Asst inventory by default.

There are no Radios in the whole squad inventory by default.

Pls Fix when able

**Comment by Geek-x104** [comment]
side?

**Comment by tanaaKa** [comment]
@Njpatman

**Comment by Njpatman** [comment]
Opfor

**Comment by tanaaKa** [comment]
Modern/RHS?

**Comment by Njpatman** [comment]
Yeah, specifically the version on the port attack mission we ran 2 sessions ago.

**Comment by tanaaKa** [comment]
https://github.com/CoalitionArma/Coalition-Reforger-Framework/pull/77
