### ISSUE TITLE
Missing binoculars, maps and radios on certain character entities

### ISSUE THREAD

**Issue by Geek-x104** [CoalitionArma/Coalition-Reforger-Framework#73]
Certain character entities are missing binoculars, maps and radios meaning that there are groups missing either binoculars, maps, radios or both.
The following list shows characters missing either binoculars, maps, radios or all 3. All the other teams (eg: OPFOR MSV MMG Team) have FTLs or SLs in their group.

List:
US:
1980:
Sniper: Radio and Map, No Binos
Spotter: Radio, Map and Binos

Heli Pilot: Radio, Map and Binos
Crew Chief/Gunner: Radio and Map, No Binos

Crewman: No Radio, Map or Binos

Modern:
Crewman: Radio and map, No Binos

OPFOR:
1980:
Heli Pilot: Radio, Map and Binos
Helicrew: Radio and Map, No Binos

Armour Crew: Radio and Map, No Binos

Sniper: Radio and Map, No Binos

Modern:
Crewman: Radio, No Binos or Map

**Comment by Geek-x104** [comment]
also, OPFOR 1980s Sniper team has no spotter

**Comment by tanaaKa** [comment]
Are you working for a PR to fix this or is this a request to have it done?

**Comment by tanaaKa** [comment]
https://github.com/CoalitionArma/Coalition-Reforger-Framework/pull/77

**Comment by Geek-x104** [comment]
I'm going to do this shortly, i have been working on my mission

**Comment by tanaaKa** [comment]
Already done for the most part, for what I could understand.

**Comment by Geek-x104** [comment]
doing the rest now, am i good to add to existing PR https://github.com/CoalitionArma/Coalition-Reforger-Framework/pull/77

**Comment by tanaaKa** [comment]
yeah just make sure you pull it first
