### ISSUE TITLE
Missing primary weapon for air/ground vehicle crews

### ISSUE THREAD

**Issue by GHPCee** [CoalitionArma/Coalition-Reforger-Framework#75]
Personal experience from CFC 4 (May 10th):

USSR pilot only had a pistol and no primary weapon.

Suggestions:

For USSR/RU crewmen, give AKS-74u. For US/NATO, unsure, probably a carbine/m16 of sorts.

**Comment by Geek-x104** [comment]
can agree this isn't ideal in case the pilot/crewman need to defned themselves

**Comment by tanaaKa** [comment]
https://github.com/CoalitionArma/Coalition-Reforger-Framework/pull/77
