### ISSUE TITLE
RHS AFRF Group Rework

### ISSUE THREAD

**Issue by Pi123263** [CoalitionArma/Coalition-Reforger-Framework#98]
The RHS AFRF Groups could use a rework to fit in with the currently default file setup and group choices I set for the vanilla factions, creating an issue as a reminder

**Comment by Geek-x104** [comment]
folders have been organized

**Comment by RandAlThor1** [comment]
This is slated to be done,
Reference: https://github.com/CoalitionArma/Coalition-Reforger-Framework/issues/144
Once roles and loadouts have been made, factions will be built up with all prefab groups to improve mission making
